import type { Metadata } from "next";
import { Header } from "./_components/Header component/Header";
import { Footer } from "./_components/Footer/Footer";
import { CartProvider } from "../context/CartContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <CartProvider>
        <Header />
        {children}
        <Toaster richColors position="top-center" />
        <Footer />
      </CartProvider>
    </div>
  );
}
