import type { Metadata } from "next";
import { Header } from "./_components/(Header component)/Header";
import { Footer } from "./_components/(Footer components)/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
