import type { Metadata } from "next";
import { LeftPanel } from "./LeftPanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row">
      <LeftPanel />
      {children}
    </div>
  );
}
